#
# vaidate generated manifest with test values that activate all templates
#
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
targetAverageUtilization: 100
resources:
  limits:
    cpu: 1.0
    memory: 768Mi
  requests:
    cpu: 100m
    memory: 700Mi
ingress:
  enabled: true
  tls:
    test:
      secretName: test-ingress-cert
      hosts:
        - test.test.edu
  hosts:
    test:
      host: test.test.edu
      paths:
        - "/"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
lifecycle:
  enabled: true
  preStop:
    enabled: true
affinity:
   podsSpanNodes: true
readiness:
  enabled: true
externalService:
  enabled: true
  name: test-db
  type: ClusterIP
  serviceAddress: 172.18.0.19
  servicePort: 3306
database:
  engine: mysql
  name: test
  hostname: test
  secretName: sql-secrets
repo: test
instance: test
image:
  repository: registry.hub.docker.com/test/test
  tag: IMAGE_TAG
memcached:
  enabled: true
  replicaCount: 1
  updateStrategy:
    type: RollingUpdate
  resources:
    limits:
      memory: 256Mi
    requests:
      memory: 256Mi
certs:
  mounted: true
  certPath: /certs/test.cert
  keyPath: /certs/test.key
  secretName: test-certs
cronjob:
  enabled: true
  jobs:
    - name: clear-expired
      schedule: "1 10 * * 6"
      command: ["/scripts/command.sh"]
      args: ["clear_expired", "7"]
daemon:
  enabled: true
  daemons:
    - name: monitor-sessions
      command: ["/scripts/command.sh"]
      args: ["monitor"]
environmentVariables:
  - name: ENV
    value: test
externalSecrets:
  enabled: true
  secrets:
    - name: test-secrets
      externalKey: secrets/secrets
      data:
        - name: django-secret
          property: django_secret
    - name: sql-secrets
      externalKey: secrets/sql-secrets
      data:
        - name: username
          property: sql_user
        - name: password
          property: sql_pass
    - name: test-certs
      externalKey: secrets/certs
      data:
        - name: test.key
          property: key
        - name: test.cert
          property: cert
environmentVariablesSecrets:
  django-secret:
    name: DJANGO_SECRET
    secretName: test-secrets
    secretKey: django-secret
