{{- if and .Values.deployment.enabled .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "django-production-chart.releaseIdentifier" . }}-autoscaler
  namespace: default
  labels:
    app.kubernetes.io/component: autoscaler
{{- include "django-production-chart.resourceLabels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "django-production-chart.releaseIdentifier" . }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.targetAverageUtilization }}
{{- end }}
