{{- if and .Values.deployment.enabled .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "django-production-chart.releaseIdentifier" . }}-autoscaler
  namespace: {{ include "django-production-chart.namespaceIdentifier" . }}
  labels:
    app.kubernetes.io/name: {{ include "django-production-chart.releaseIdentifier" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- include "django-production-chart.resourceLabels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "django-production-chart.releaseIdentifier" . }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.targetAverageUtilization }}
{{- end }}
