{{- $dot := . }}
{{- range $name, $map := .Values.configmaps }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-%s" ( include "django-production-chart.releaseIdentifier" $dot ) $name }}
  namespace: {{ include "django-production-chart.namespaceIdentifier" $dot }}
data:
{{ toYaml $map | indent 2 }}
{{- end -}}
