{{- if .Values.cronjob.enabled }}
{{- $dot := . -}}
{{- $namespace := include "django-production-chart.namespaceIdentifier" . -}}
{{- range .Values.cronjob.jobs -}}
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ printf "%s-cronjob-%s" ( include "django-production-chart.releaseIdentifier" $dot ) .name }}
  namespace: {{ $namespace }}
  labels:
    app.kubernetes.io/name: {{ include "django-production-chart.releaseIdentifier" $dot }}
    helm.sh/chart: {{ include "django-production-chart.chart" $dot }}
    app.kubernetes.io/instance: {{ $dot.Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ $dot.Release.Service | quote }}
{{- if $dot.Values.securityPolicy.enabled }}
{{- if $dot.Values.securityPolicy.cronjob }}
{{- if $dot.Values.securityPolicy.cronjob.skipCheck }}
  annotations:
{{- range $index, $value:= $dot.Values.securityPolicy.cronjob.skipCheck }}
    checkov.io/skip{{ add $index 1 }}: {{ $value | quote }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
spec:
  schedule: {{ .schedule | quote }}
  concurrencyPolicy: {{ default "Forbid" .concurrencyPolicy | quote }}
  successfulJobsHistoryLimit: {{ default 0 .successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ default 3 .failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: {{ $dot.Release.Name | quote }}
            cron: {{ .name | quote }}
{{- if $dot.Values.securityPolicy.enabled }}
{{- if $dot.Values.securityPolicy.cronjob }}
{{- if $dot.Values.securityPolicy.cronjob.annotations }}
          annotations:
{{ toYaml $dot.Values.securityPolicy.cronjob.annotations | indent 12 }}
{{- end }}
{{- end }}
{{- end }}
        spec:
{{- if $dot.Values.securityPolicy.enabled }}
{{- if $dot.Values.securityPolicy.cronjob }}
{{- if $dot.Values.securityPolicy.cronjob.template }}
{{ toYaml $dot.Values.securityPolicy.cronjob.template | indent 10 }}
{{- end }}
{{- end }}
{{- end }}
{{- if .serviceAccountName }}
          serviceAccountName: {{ .serviceAccountName }}
{{- else }}
          automountServiceAccountToken: false
{{- end }}
          restartPolicy: {{ default "OnFailure" .restartPolicy | quote }}
{{- include "django-production-chart.specContainerBase" $dot | nindent 10 -}}
{{- include "django-production-chart.specContainerResources" (or .resources $dot.Values.resources) | nindent 14 -}}
{{- include "django-production-chart.specContainerEnv" $dot | nindent 14 -}}
{{- include "django-production-chart.specContainerCommand" (dict "command" .command "args" .args) | nindent 14 -}}
{{- include "django-production-chart.specContainerSidecars" $dot | indent 10 -}}
{{ printf "\n" }}
{{- end -}}
{{- end -}}