{{- if .Values.cronjob.enabled }}
{{- $dot := . -}}
{{- range .Values.cronjob.jobs -}}
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ printf "%s-cronjob-%s" ( include "django-production-chart.releaseIdentifier" $dot ) .name }}
  labels:
    app.kubernetes.io/name: {{ include "django-production-chart.releaseIdentifier" $dot }}
    helm.sh/chart: {{ include "django-production-chart.chart" $dot }}
    app.kubernetes.io/instance: {{ $dot.Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ $dot.Release.Service | quote }}
spec:
  schedule: {{ .schedule | quote }}
  concurrencyPolicy: {{ default "Forbid" .concurrencyPolicy | quote }}
  successfulJobsHistoryLimit: {{ default 0 .successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ default 3 .failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: {{ $dot.Release.Name | quote }}
            cron: {{ .name | quote }}
        spec:
          restartPolicy: {{ default "OnFailure" .restartPolicy | quote }}
{{- include "django-production-chart.specContainerBase" $dot | nindent 10 -}}
{{- include "django-production-chart.specContainerResources" $dot | nindent 14 -}}
{{- include "django-production-chart.specContainerEnv" $dot | nindent 14 -}}
{{- include "django-production-chart.specContainerCommand" (dict "command" .command "args" .args) | nindent 14 -}}
{{ printf "\n" }}
{{- end -}}
{{- end -}}