{{- if .Values.cronjob.enabled }}
{{- $dot := . -}}
{{- $namespace := include "django-production-chart.namespaceIdentifier" . -}}
{{- range .Values.cronjob.jobs -}}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ printf "%s-cronjob-%s" ( include "django-production-chart.releaseIdentifier" $dot ) .name }}
  namespace: {{ $namespace }}
  labels:
    app.kubernetes.io/name: {{ include "django-production-chart.releaseIdentifier" $dot }}
    app.kubernetes.io/instance: {{ $dot.Release.Name | quote }}
{{- include "django-production-chart.resourceLabels" $dot | nindent 4 }}
{{- if $dot.Values.securityPolicy.enabled }}
  annotations:
{{ include "django-production-chart.securityPolicyAnnotations" $dot.Values.securityPolicy.cronjob | indent 4 }}
{{- end }}
spec:
  schedule: {{ .schedule | quote }}
  concurrencyPolicy: {{ default "Forbid" .concurrencyPolicy | quote }}
  successfulJobsHistoryLimit: {{ default 0 .successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ default 3 .failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: {{ $dot.Release.Name | quote }}
            cron: {{ .name | quote }}
            app.kubernetes.io/component: cronjob
{{- if $dot.Values.securityPolicy.enabled }}
          annotations:
{{ include "django-production-chart.securityPolicyAnnotations" $dot.Values.securityPolicy.cronjob | indent 12 }}
{{- end }}
        spec:
{{- if $dot.Values.securityPolicy.enabled }}
          securityContext:
{{ include "django-production-chart.securityPolicyContext" $dot.Values.securityPolicy.cronjob | indent 12 }}
{{- end }}
{{- if .serviceAccountName }}
          serviceAccountName: {{ .serviceAccountName }}
{{- else }}
          automountServiceAccountToken: false
{{- end }}
          restartPolicy: {{ default "OnFailure" .restartPolicy | quote }}
{{ include "django-production-chart.specContainerContainers" (dict "root" . "type" "initContainers" "containers" .initContainers) | indent 10 }}
{{- include "django-production-chart.specContainerBase" ( merge ( dict "containerImage" .image "containerName" .name ) $dot ) | nindent 10 -}}
{{- include "django-production-chart.specContainerResources" (or .resources $dot.Values.resources) | nindent 14 -}}
{{- include "django-production-chart.specContainerEnv" $dot | nindent 14 -}}
{{- include "django-production-chart.specContainerCommand" (dict "command" .command "args" .args) | nindent 14 -}}
{{- include "django-production-chart.specContainerContainers" (dict "root" $dot "containers" .sidecarContainers) | indent 10 -}}
{{ printf "\n" }}
{{- end -}}
{{- end -}}
