{{- if .Values.daemon.enabled }}
{{- $dot := . }}
{{- $release_id := ( include "django-production-chart.releaseIdentifier" . ) }}
{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-daemon" $release_id }}
  labels:
    app.kubernetes.io/name: {{ printf "%s-daemon" $release_id }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    role: management-command-daemon
spec:
  clusterIP: None
  ports:
    - name: metrics
      port: 8080
      targetPort: metrics
      protocol: TCP
  selector:
    role: management-command-daemon
    app.kubernetes.io/instance: {{ $release_id }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ printf "%s-daemon" $release_id }}
spec:
  endpoints:
    - port: metrics
  selector:
    matchLabels:
      role: management-command-daemon
      app.kubernetes.io/instance: {{ $release_id }}
{{- end }}
{{- range .Values.daemon.daemons }}
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: {{ printf "%s-daemon-%s" $release_id .name }}
  labels:
    app.kubernetes.io/name: {{ printf "%s-daemon-%s" $release_id .name }}
    app.kubernetes.io/instance: {{ $release_id }}
    helm.sh/chart: {{ include "django-production-chart.chart" $dot }}
spec:
  replicas: {{ default 1 .replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ printf "%s-daemon-%s" $release_id .name }}
      app.kubernetes.io/instance: {{ $release_id }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ printf "%s-daemon-%s" $release_id .name }}
        app.kubernetes.io/instance: {{ $release_id }}
        role: management-command-daemon
    spec:
{{- include "django-production-chart.specContainerBase" $dot | nindent 6 }}
          ports:
            - name: metrics
              containerPort: 8080
{{- include "django-production-chart.specContainerResources" $dot | nindent 10 }}
{{- include "django-production-chart.specContainerEnv" $dot | nindent 10 }}
{{- include "django-production-chart.specContainerCommand" (dict "command" .command "args" .args) | nindent 10 }}
{{- end }}
{{- end }}
