{{- if .Values.daemon.enabled }}
{{- $dot := . }}
{{- $release_id := ( include "django-production-chart.releaseIdentifier" . ) }}
{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ printf "%s-daemon" $release_id }}
spec:
  endpoints:
    - port: 8080
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ $release_id }}
      role: "management-command-daemon"
{{- end }}
{{- range .Values.daemon.daemons }}
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: {{ printf "%s-daemon-%s" $release_id .name }}
  labels:
    app.kubernetes.io/name: {{ printf "%s-daemon-%s" $release_id .name }}
    app.kubernetes.io/instance: {{ $release_id }}
    helm.sh/chart: {{ include "django-production-chart.chart" $dot }}
spec:
  replicas: {{ default 1 .replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ printf "%s-daemon-%s" $release_id .name }}
      app.kubernetes.io/instance: {{ $release_id }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ printf "%s-daemon-%s" $release_id .name }}
        app.kubernetes.io/instance: {{ $release_id }}
        role: "management-command-daemon"
    spec:
{{- include "django-production-chart.specContainerBase" $dot | nindent 6 -}}
{{- include "django-production-chart.specContainerResources" $dot | nindent 10 -}}
{{- include "django-production-chart.specContainerEnv" $dot | nindent 10 -}}
{{- include "django-production-chart.specContainerCommand" (dict "command" .command "args" .args) | nindent 10 -}}
{{- end }}
{{- end }}
