{{- if .Values.daemon.enabled }}
{{- $dot := . }}
{{- $component := management-command-daemon }}
{{- $release_id := ( include "django-production-chart.releaseIdentifier" . ) }}
{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-daemon" $release_id }}
  labels:
    app.kubernetes.io/component: {{ $component }}
{{- include "django-production-chart.resourceLabels" $dot | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - name: metrics
      port: 9100
      targetPort: metrics
      protocol: TCP
  selector:
    app.kubernetes.io/component: {{ $component }}
    app.kubernetes.io/instance: {{ $release_id }}
    app.kubernetes.io/name: {{ .Release.Name }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ printf "%s-daemon" $release_id }}
spec:
  endpoints:
    - port: metrics
  selector:
    matchLabels:
      app.kubernetes.io/component: {{ $component }}
      app.kubernetes.io/instance: {{ $release_id }}
      app.kubernetes.io/name: {{ .Release.Name }}
{{- end }}
{{- range .Values.daemon.daemons }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-daemon-%s" $release_id .name }}
  labels:
    app.kubernetes.io/component: {{ printf "%s-%s" $component .name }}
{{- include "django-production-chart.resourceLabels" $dot | nindent 4 }}
{{- if $dot.Values.securityPolicy.enabled }}
{{- if $dot.Values.securityPolicy.daemon }}
{{- if $dot.Values.securityPolicy.daemon.skipCheck }}
  annotations:
{{- range $index, $value:= $dot.Values.securityPolicy.daemon.skipCheck }}
    checkov.io/skip{{ add $index 1 }}: {{ $value | quote }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
spec:
  replicas: {{ default 1 .replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
      app.kubernetes.io/instance: {{ $release_id }}
      app.kubernetes.io/component: {{ printf "%s-%s" $component .name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}
        app.kubernetes.io/instance: {{ $release_id }}
        app.kubernetes.io/component: {{ printf "%s-%s" $component .name }}
{{- if $dot.Values.securityPolicy.enabled }}
{{- if $dot.Values.securityPolicy.daemon }}
{{- if $dot.Values.securityPolicy.daemon.annotations }}
      annotations:
{{ toYaml $dot.Values.securityPolicy.daemon.annotations | indent 8 }}
{{- end }}
{{- end }}
{{- end }}
    spec:
{{- if $dot.Values.securityPolicy.enabled }}
{{- if $dot.Values.securityPolicy.daemon }}
{{- if $dot.Values.securityPolicy.daemon.spec }}
{{ toYaml $dot.Values.securityPolicy.daemon.spec | indent 6 }}
{{- end }}
{{- end }}
{{- end }}
{{- include "django-production-chart.specContainerBase" $dot | nindent 6 }}
          ports:
            - name: metrics
              containerPort: 9100
{{- include "django-production-chart.specContainerResources" (or .resources $dot.Values.resources) | nindent 10 }}
{{- include "django-production-chart.specContainerEnv" $dot | nindent 10 }}
{{- include "django-production-chart.specContainerCommand" (dict "command" .command "args" .args) | nindent 10 }}
{{- end }}
{{- end }}
