{{- if .Values.daemon.enabled }}
{{- $component := "management-command-daemon" }}
{{- $_ := set .Values "releaseIdentifier" ( include "django-production-chart.releaseIdentifier" . ) }}
{{- $_ := set .Values "namespaceIdentifier" ( include "django-production-chart.namespaceIdentifier" . ) }}
{{- $_ := set .Values "instanceIdentifier" ( include "django-production-chart.instanceIdentifier" . ) }}
{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
{{- $name := printf "%s-daemon" $.Values.releaseIdentifier }}
{{- if and .Values.namespace .Values.namespace.enabled }}
{{- $name = "daemon" }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  namespace: {{ $.Values.namespaceIdentifier }}
  labels:
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/instance: {{ $.Values.instanceIdentifier }}
    app.kubernetes.io/component: {{ $component }}
    role: {{ $component }}
{{- include "django-production-chart.resourceLabels" $ | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - name: metrics
      port: 9100
      targetPort: metrics
      protocol: TCP
  selector:
    role: management-command-daemon
    app.kubernetes.io/instance: {{ $.Values.instanceIdentifier }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ $name }}
  namespace: {{ $.Values.namespaceIdentifier }}
  labels:
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/instance: {{ $.Values.instanceIdentifier }}
    app.kubernetes.io/component: {{ $component }}
{{- include "django-production-chart.resourceLabels" $ | nindent 4 }}
spec:
  endpoints:
    - port: metrics
  selector:
    matchLabels:
      role: {{ $component }}
      app.kubernetes.io/instance: {{ $.Values.instanceIdentifier }}
{{- end }}
{{- range .Values.daemon.daemons }}
{{- $daemonName := printf "%s-daemon-%s" $.Values.releaseIdentifier .name }}
{{- if and $.Values.metrics.enabled $.Values.metrics.serviceMonitor.enabled }}
{{- $daemonName = .name }}
{{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $daemonName }}
  namespace: {{ $.Values.namespaceIdentifier }}
  labels:
    app.kubernetes.io/name: {{ $daemonName }}
    app.kubernetes.io/instance: {{ $.Values.instanceIdentifier }}
    app.kubernetes.io/component: {{ $component }}
    role: {{ $component }}
{{- include "django-production-chart.resourceLabels" $ | nindent 4 }}
{{- if $.Values.securityPolicy.enabled }}
  annotations:
{{ include "django-production-chart.securityPolicyAnnotations" $.Values.securityPolicy.daemon | indent 4 }}
{{- end }}
spec:
  replicas: {{ default 1 .replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $daemonName }}
      app.kubernetes.io/instance: {{ $.Values.instanceIdentifier }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ $daemonName }}
        app.kubernetes.io/instance: {{ $.Values.instanceIdentifier }}
        role: management-command-daemon
{{- if $.Values.securityPolicy.enabled }}
      annotations:
{{ include "django-production-chart.securityPolicyAnnotations" $.Values.securityPolicy.daemon | indent 8 }}
{{- end }}
    spec:
{{- if $.Values.securityPolicy.enabled }}
{{ include "django-production-chart.securityPolicySpec" $.Values.securityPolicy.daemon | indent 6 }}
{{- end }}
{{ include "django-production-chart.specVolumes" $ | indent 6 }}
{{ include "django-production-chart.specContainers" (dict "root" . "type" "initContainers" "containers" .initContainers) | indent 6 }}
{{- include "django-production-chart.specContainerBase" $ | nindent 6 }}
          ports:
            - name: metrics
              containerPort: 9100
{{- include "django-production-chart.specContainerResources" (or .resources $.Values.resources) | nindent 10 }}
{{- include "django-production-chart.specContainerEnv" $ | nindent 10 }}
{{- include "django-production-chart.specContainerCommand" (dict "command" .command "args" .args) | nindent 10 }}
{{- include "django-production-chart.specContainers" (dict "root" $ "containers" .sidecarContainers) | indent 6 -}}
{{- end }}
{{- end }}
