{{- if .Values.deployment.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "django-production-chart.releaseIdentifier" . }}
  namespace: {{ include "django-production-chart.namespaceIdentifier" . }}
  labels:
    app.kubernetes.io/name: {{ include "django-production-chart.releaseIdentifier" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: deployment
{{- include "django-production-chart.resourceLabels" . | nindent 4 }}
{{- if .Values.securityPolicy.enabled }}
  annotations:
{{ include "django-production-chart.securityPolicyAnnotations" .Values.securityPolicy.deployment | indent 4 }}
{{- end }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "django-production-chart.releaseIdentifier" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "django-production-chart.releaseIdentifier" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
{{- if .Values.securityPolicy.enabled }}
      annotations:
{{ include "django-production-chart.securityPolicyAnnotations" .Values.securityPolicy.deployment | indent 8 }}
{{- end }}
    spec:
{{- if .Values.securityPolicy.enabled }}
{{ include "django-production-chart.securityPolicySpec" .Values.securityPolicy.deployment | indent 6 }}
{{- end }}
{{ include "django-production-chart.specControllerScheduling" . | indent 6 }}
{{ include "django-production-chart.specContainerContainers" (dict "root" . "containers" .Values.sidecarContainers) | indent 6 }}{{ include "django-production-chart.specContainer" . | indent 6 }}
{{ include "django-production-chart.specContainerLifecycle" . | indent 10 }}
{{ include "django-production-chart.specContainerProbes" . | indent 10 }}
{{ include "django-production-chart.specContainerContainers" (dict "root" . "type" "initContainers" "containers" .Values.initContainers) | indent 6 }}
{{- end -}}
