apiVersion: batch/v1
kind: Job
metadata:
  name: "{{.Release.Name}}"
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    helm.sh/chart: "{{.Chart.Name}}-{{.Chart.Version}}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "django-production-chart.releaseIdentifier" . }}-release-job-{{ .Values.image.tag | trunc 7 }}-{{ randAlphaNum 3 | lower}}
  labels:
    app.kubernetes.io/name: {{ include "django-production-chart.releaseIdentifier" . }}
    helm.sh/chart: {{ include "django-production-chart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- if .Values.securityPolicy.enabled }}
  annotations:
    checkov.io/skip1: CKV_K8S_40=Django-container base sets uid 1000
    checkov.io/skip2: CKV_K8S_22=Readonly root file system too restictive
{{- end }}
spec:
  backoffLimit: 1
  template:
    metadata:
      name: "{{.Release.Name}}"
      labels:
        app.kubernetes.io/managed-by: {{.Release.Service | quote }}
        app.kubernetes.io/instance: {{.Release.Name | quote }}
        helm.sh/chart: "{{.Chart.Name}}-{{.Chart.Version}}"
{{- if .Values.securityPolicy.enabled }}
{{- if .Values.securityPolicy.deployment }}
{{- if .Values.securityPolicy.deployment.annotations }}
      annotations:
{{ toYaml .Values.securityPolicy.deployment.annotations | indent 8 }}
{{- end }}
{{- end }}
{{- end }}
    spec:
{{- if .Values.securityPolicy.enabled }}
{{- if .Values.securityPolicy.deployment }}
{{- if .Values.securityPolicy.deployment.spec }}
{{ toYaml .Values.securityPolicy.deployment.spec | indent 6 }}
{{- end }}
{{- end }}
{{- end }}
      restartPolicy: "Never"
{{- include "django-production-chart.specContainerBase" . | nindent 6 -}}
{{- include "django-production-chart.specContainerResources" . | nindent 10 -}}
{{- include "django-production-chart.specContainerEnv" . | nindent 10 -}}
{{- include "django-production-chart.specContainerCommand" (dict "command" (list "/scripts/deploy.sh")) | nindent 10 -}}
{{- include "django-production-chart.specContainerPorts" . | nindent 10 -}}
{{- include "django-production-chart.specContainerProbes" . | nindent 10 -}}
