apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "django-production-chart.releaseIdentifier" . }}
  labels:
    app.kubernetes.io/name: {{ include "django-production-chart.releaseIdentifier" . }}
    helm.sh/chart: {{ include "django-production-chart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- if .Values.securityPolicy.enabled }}
  annotations:
    checkov.io/skip1: CKV_K8S_8=Liveness probe more trouble than it's worth
    checkov.io/skip2: CKV_K8S_22=Readonly root file system too restictive
    checkov.io/skip3: CKV_K8S_25=Add capability for metrics api
    checkov.io/skip4: CKV_K8S_31=Seccomp default breaks HPA metrics api queries
    checkov.io/skip5: CKV_K8S_40=Django-container base sets uid 1000
{{- end }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "django-production-chart.releaseIdentifier" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "django-production-chart.releaseIdentifier" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
{{- if .Values.securityPolicy.enabled }}
{{- if .Values.securityPolicy.deployment }}
{{- if .Values.securityPolicy.deployment.annotations }}
      annotations:
{{ toYaml .Values.securityPolicy.deployment.annotations | indent 8 }}
{{- end }}
{{- end }}
{{- end }}
    spec:
{{- if .Values.securityPolicy.enabled }}
{{- if .Values.securityPolicy.deployment }}
{{- if .Values.securityPolicy.deployment.spec }}
{{ toYaml .Values.securityPolicy.deployment.spec | indent 6 }}
{{- end }}
{{- end }}
{{- end }}
{{- include "django-production-chart.specControllerScheduling" . | nindent 6 -}}
{{- include "django-production-chart.specContainer" . | nindent 6 -}}
{{- include "django-production-chart.specContainerLifecycle" . | nindent 10 -}}
{{- include "django-production-chart.specContainerProbes" . | nindent 10 -}}
