{{- if and .Values.deployment.enabled .Values.deploymentInitialization.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "django-production-chart.releaseIdentifier" . }}-release-job-{{ .Values.image.tag | trunc 7 }}-{{ randAlphaNum 3 | lower}}
  namespace: {{ include "django-production-chart.namespaceIdentifier" . }}
  labels:
    app.kubernetes.io/name: {{ printf "%s-release-job" ( include "django-production-chart.releaseIdentifier" . ) }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/component: release-job
{{- include "django-production-chart.resourceLabels" . | nindent 4 }}
{{- if .Values.securityPolicy.enabled }}
  annotations:
{{- include "django-production-chart.securityPolicyAnnotations" .Values.securityPolicy.deploy | indent 4 }}
{{- end }}
spec:
  backoffLimit: 1
  template:
    metadata:
      name: "{{.Release.Name}}"
      namespace: {{ include "django-production-chart.namespaceIdentifier" . }}
      labels:
        app.kubernetes.io/name: {{ printf "%s-release-job" ( include "django-production-chart.releaseIdentifier" . ) }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        app.kubernetes.io/component: release-job
{{- include "django-production-chart.resourceLabels" . | nindent 8 }}
{{- if .Values.securityPolicy.enabled }}
      annotations:
{{- include "django-production-chart.securityPolicyAnnotations" .Values.securityPolicy.deployment | indent 8 }}
{{- end }}
    spec:
{{- if .Values.securityPolicy.enabled }}
{{- include "django-production-chart.securityPolicySpec" .Values.securityPolicy.deployment | indent 6 }}
{{- end }}
      restartPolicy: "Never"
{{- include "django-production-chart.specContainerBase" . | nindent 6 -}}
{{- include "django-production-chart.specContainerResources" .Values.resources | nindent 10 -}}
{{- include "django-production-chart.specContainerEnv" . | nindent 10 -}}
{{- include "django-production-chart.specContainerCommand" (dict "command" (list "/scripts/deploy.sh")) | nindent 10 -}}
{{- include "django-production-chart.specContainerPorts" . | nindent 10 -}}
{{- include "django-production-chart.specContainerProbes" . | nindent 10 -}}
{{- end }}
