apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "django-production-chart.releaseIdentifier" . }}
  labels:
    app.kubernetes.io/name: {{ include "django-production-chart.releaseIdentifier" . }}
    helm.sh/chart: {{ include "django-production-chart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "django-production-chart.releaseIdentifier" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "django-production-chart.releaseIdentifier" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
{{- include "django-production-chart.specContainer" . | nindent 6 -}}
