{{- if .Values.deployment.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "django-production-chart.releaseIdentifier" . }}
  labels:
    app.kubernetes.io/component: deployment
{{- include "django-production-chart.resourceLabels" . | nindent 4 }}
{{- if .Values.securityPolicy.enabled }}
{{- if .Values.securityPolicy.deployment }}
{{- if .Values.securityPolicy.deployment.skipCheck }}
  annotations:
{{- range $index, $value:= .Values.securityPolicy.deployment.skipCheck }}
    checkov.io/skip{{ add $index 1 }}: {{ $value | quote }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
{{- include "django-production-chart.baseLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
{{- include "django-production-chart.baseLabels" . | nindent 8 }}
{{- if .Values.securityPolicy.enabled }}
{{- if .Values.securityPolicy.deployment }}
{{- if .Values.securityPolicy.deployment.annotations }}
      annotations:
{{ toYaml .Values.securityPolicy.deployment.annotations | indent 8 }}
{{- end }}
{{- end }}
{{- end }}
    spec:
{{- if .Values.securityPolicy.enabled }}
{{- if .Values.securityPolicy.deployment }}
{{- if .Values.securityPolicy.deployment.spec }}
{{ toYaml .Values.securityPolicy.deployment.spec | indent 6 }}
{{- end }}
{{- end }}
{{- end }}
{{- include "django-production-chart.specControllerScheduling" . | nindent 6 -}}
{{- include "django-production-chart.specContainer" . | nindent 6 -}}
{{- include "django-production-chart.specContainerLifecycle" . | nindent 10 -}}
{{- include "django-production-chart.specContainerProbes" . | nindent 10 -}}
{{- end }}
