{{- if .Values.externalSecrets.enabled }}
{{- range .Values.externalSecrets.secrets }}
---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ .name }}
  namespace: default
spec:
  backendType: vault
  data:
{{- $key := .externalKey }}
{{- range .data }}
    - name: {{ .name }}
      key: {{ $key }}
      property: {{ .property }}
{{- end -}}
{{- end -}}
{{- end -}}
