{{- if .Values.externalSecrets.enabled }}
{{- $dot := . }}
{{- $namespace := include "django-production-chart.namespaceIdentifier" . -}}
{{- range .Values.externalSecrets.secrets }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .name }}
  namespace: {{ $namespace }}
spec:
  secretStoreRef:
    name: mosler-axdd
    kind: ClusterSecretStore
  data:
{{- $key := trimPrefix "axdd/kv/data/" .externalKey }}
{{- range .data }}
{{- if $dot.Values.securityPolicy.enabled }}
    # checkov:skip=CKV_SECRET_6 key does not define literal secret
{{- end }}
    - secretKey: {{ .name }}
      remoteRef:
        key: {{ $key }}
        property: {{ .property }}
{{- end -}}
{{- end -}}
{{- end -}}
