{{- if .Values.ingress.enabled }}
{{ $_ := set .Values "releaseIdentifier" ( include "django-production-chart.releaseIdentifier" . ) }}
{{ $_ := set .Values "namespaceIdentifier" ( include "django-production-chart.namespaceIdentifier" . ) }}
{{- $fullName := include "django-production-chart.fullname" . -}}
{{- $ingressPath := .Values.ingress.path -}}
{{- $branch := .Values.branch}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  namespace: {{ $.Values.namespaceIdentifier }}
  labels:
    app.kubernetes.io/name: {{ .Values.releaseIdentifier }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: ingress
{{- include "django-production-chart.resourceLabels" . | nindent 4 }}
  annotations:
{{- with .Values.ingress.annotations }}
{{ toYaml . | indent 4 }}
{{- end }}
{{- if .Values.securityPolicy.enabled }}
{{- include "django-production-chart.securityPolicyAnnotations" .Values.securityPolicy.ingress | indent 4 }}
{{- end }}
spec:
  ingressClassName: {{ default "nginx" .Values.ingress.type | quote }}
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ . }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $.Values.releaseIdentifier }}
                port:
                  name: http
        {{- end }}
  {{- end }}
{{- end }}
