{{- if and .Values.memcached.enabled .Values.memcached.mcrouter.enabled }}
{{- $memcachedService := printf "%s-memcached" ( include "django-production-chart.releaseIdentifier" . ) -}}
{{- $releaseNamespace := .Release.Namespace -}}
{{- $controller := .Values.memcached.mcrouter.controller | default "daemonset" -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-mcrouter" ( include "django-production-chart.releaseIdentifier" . ) }}
  namespace: {{ $releaseNamespace }}
  labels:
    app.kubernetes.io/name: {{ include "django-production-chart.releaseIdentifier" . }}
    helm.sh/chart: {{ include "django-production-chart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
spec:
  clusterIP: None
  ports:
  - name: mcrouter-port
    port: {{ default 5000 .Values.memcached.mcrouter.params.port }}
    targetPort: mcrouter-port
  selector:
    app.kubernetes.io/name:  {{ include "django-production-chart.releaseIdentifier" . }} 
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-mcrouter-configmap" ( include "django-production-chart.releaseIdentifier" . ) }}
  namespace: {{ $releaseNamespace }}
  labels:
    app.kubernetes.io/name: {{ include "django-production-chart.releaseIdentifier" . }}
    helm.sh/chart: {{ include "django-production-chart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
data:
  config.json: |-
{{- if .Values.memcached.mcrouter.params.configFile }}{{ range .Files.Lines .Values.memcached.mcrouter.params.configFile }}
    {{ . }}{{ end }}
{{- else }}
    {
      "pools": {
        "A": {
          "servers": [
            {{- range $i, $e := until (.Values.memcached.replicaCount | int) }}
            "{{ $memcachedService }}-{{ $i }}.{{ $memcachedService }}.{{ $releaseNamespace }}.svc.cluster.local:11211",
            {{- end }}
          ]
        }
      },
      "route": "PoolRoute|A"
    }
{{- end }}
{{- if eq $controller "daemonset" }}
---
apiVersion: {{ template "daemonset.apiVersion" . }}
kind: DaemonSet
metadata:
  name: {{ printf "%s-mcrouter" ( include "django-production-chart.releaseIdentifier" . ) }}
  labels:
    app.kubernetes.io/name: {{ include "django-production-chart.releaseIdentifier" . }}
    helm.sh/chart: {{ include "django-production-chart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
spec:
  selector:
    matchLabels:
      app: {{ printf "%s-mcrouter" ( include "django-production-chart.releaseIdentifier" . ) }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ printf "%s-mcrouter" ( include "django-production-chart.releaseIdentifier" . ) }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
    spec:
      containers:
      - name: {{ printf "%s-mcrouter" ( include "django-production-chart.releaseIdentifier" . ) }}
        image: {{ default "jphalip/mcrouter:0.36.0" .Values.memcached.mcrouter.image }}
        imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}
        command: ["mcrouter"]
        args:
        - -p {{ default 5000 .Values.memcached.mcrouter.params.port }}
        - --config-file=/etc/mcrouter/config.json
        volumeMounts:
        - name: config
          mountPath: /etc/mcrouter
        ports:
        - name: mcrouter-port
          containerPort: {{ default 5000 .Values.memcached.mcrouter.params.port }}
          hostPort: {{ default 5000 .Values.memcached.mcrouter.daemonsetParams.hostPort }}
        livenessProbe:
          tcpSocket:
            port: mcrouter-port
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          tcpSocket:
            port: mcrouter-port
          initialDelaySeconds: 5
          timeoutSeconds: 1
        resources:
{{ toYaml .Values.resources | indent 10 }}
      volumes:
      - name: config
        configMap:
          name: {{ printf "%s-mcrouter-configmap" ( include "django-production-chart.releaseIdentifier" . ) }}
{{- end -}}
{{- end -}}
