{{- if .Values.memcached.enabled }}
{{- $command := .Values.memcached.command | default (list "memcached" "-m" "64" "-o" "modern" "-v") -}}
{{- $extraArgs := .Values.memcached.extraArgs | default "" -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-memcached" ( include "django-production-chart.releaseIdentifier" . ) }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ printf "%s-memcached" ( include "django-production-chart.releaseIdentifier" . ) }}
    helm.sh/chart: {{ include "django-production-chart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
{{- if .Values.serviceAnnotations -}}
  annotations:
{{ toYaml .Values.serviceAnnotations | indent 4 }}
{{- end }}
spec:
  clusterIP: None
  ports:
  - name: memcache
    port: 11211
    targetPort: memcache
{{- if .Values.metrics.enabled }}
  - name: metrics
    port: 9150
    targetPort: metrics
{{- end }}
  selector:
    app.kubernetes.io/name: {{ printf "%s-memcached" ( include "django-production-chart.releaseIdentifier" . ) }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ printf "%s-memcached" ( include "django-production-chart.releaseIdentifier" . ) }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ printf "%s-memcached" ( include "django-production-chart.releaseIdentifier" . ) }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    helm.sh/chart: {{ include "django-production-chart.chart" . }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ printf "%s-memcached" ( include "django-production-chart.releaseIdentifier" . ) }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  endpoints:
  - port: metrics
{{- end }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ printf "%s-memcached" ( include "django-production-chart.releaseIdentifier" . ) }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ printf "%s-memcached" ( include "django-production-chart.releaseIdentifier" . ) }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    helm.sh/chart: {{ include "django-production-chart.chart" . }}
{{- if .Values.securityPolicy.enabled }}
  annotations:
    checkov.io/skip1: CKV_K8S_8=Liveness probe
    checkov.io/skip2: CKV_K8S_9=Prom memcached exporter readiness
    checkov.io/skip3: CKV_K8S_10=Prom memcached exporter cpu requests
    checkov.io/skip4: CKV_K8S_11=Prom memcached exporter cpu limits
    checkov.io/skip5: CKV_K8S_12=Prom memcached exporter memory requests
    checkov.io/skip6: CKV_K8S_13=Prom memcached exporter memory limits
    checkov.io/skip7: CKV_K8S_14=Prom memcached exporter image tag latest
    checkov.io/skip8: CKV_K8S_22=Readonly root file system
    checkov.io/skip9: CKV_K8S_23=Memcached run as specfic user
    checkov.io/skip11: CKV_K8S_40=Memcached run as high uid
{{- end }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ printf "%s-memcached" ( include "django-production-chart.releaseIdentifier" . ) }}
      app.kubernetes.io/instance: {{ .Release.Name | quote }}
  serviceName: {{ printf "%s-memcached" ( include "django-production-chart.releaseIdentifier" . ) }}
  replicas: {{ .Values.memcached.replicaCount }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ printf "%s-memcached" ( include "django-production-chart.releaseIdentifier" . ) }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
{{- with .Values.podLabels }}
{{ toYaml . | indent 8 }}
{{- end}}
{{- if .Values.securityPolicy.enabled }}
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: "runtime/default"
{{- end }}
{{- with .Values.podAnnotations }}
{{- if not .Values.securityPolicy.enabled }}
      annotations:
{{- end }}
{{ toYaml . | indent 8 }}
{{- end }}
    spec:
{{- if .Values.securityPolicy.enabled }}
      automountServiceAccountToken: false
{{- end }}
      containers:
      - name: {{ printf "%s-memcached" ( include "django-production-chart.releaseIdentifier" . ) }}
        image: {{ default "memcached:1.5.21" .Values.memcached.image | quote }}
        imagePullPolicy: {{ default "Always" .Values.imagePullPolicy | quote }}
{{ include "django-production-chart.specContainerCommand" (dict "command" $command "args" $extraArgs) | indent 8}}
{{- if .Values.securityPolicy.enabled }}
        securityContext:
          runAsNonRoot: true
          runAsUser: 11211
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
{{- end }}
        ports:
        - name: memcache
          containerPort: 11211
{{- if .Values.memcached.liveness }}
  {{- if .Values.memcached.liveness.enabled }}
        livenessProbe:
          tcpSocket:
            port: memcache
          initialDelaySeconds: 30
          timeoutSeconds: 5
  {{- end }}
{{- end }}
        readinessProbe:
          tcpSocket:
            port: memcache
          initialDelaySeconds: 5
          timeoutSeconds: 1
{{- if .Values.memcached.resources }}
        resources:
{{ toYaml .Values.memcached.resources | indent 10 }}
{{- end }}
{{- if .Values.metrics.enabled }}
      - name: metrics
        image: "prom/memcached-exporter:latest"
        imagePullPolicy: {{ default "Always" .Values.metrics.imagePullPolicy | quote }}
{{- if .Values.securityPolicy.enabled }}
        securityContext:
          runAsNonRoot: true
          runAsUser: 65534
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
{{- end }}
        ports:
        - name: metrics
          containerPort: 9150
{{- if .Values.metrics.resources }}
        resources:
{{ toYaml .Values.metrics.resources | indent 10 }}
{{- end }}
{{- end }}
{{- with .Values.extraContainers }}
{{ tpl . $ | indent 6 }}
{{- end }}
{{- with .Values.extraVolumes }}
      volumes:
{{ tpl . $ | indent 6 }}
{{- end }}
{{- with .Values.memcached.nodeSelector }}
      nodeSelector:
{{ toYaml . | trim | indent 8}}
{{- end }}
{{- with .Values.memcached.tolerations }}
      tolerations:
{{ toYaml . | trim | indent 8}}
{{- end }}
{{- with .Values.memcached.affinity }}
      affinity:
{{ toYaml . | trim | indent 8}}
{{- end }}
  updateStrategy:
    type: {{ .Values.memcached.updateStrategy.type }}
    {{- if (eq "Recreate" .Values.memcached.updateStrategy.type) }}
    rollingUpdate: null
    {{- end }}
{{- end -}}
