{{- if and .Values.namespace .Values.namespace.enabled -}}
{{- $_ := set .Values "releaseIdentifier" ( include "django-production-chart.releaseIdentifier" . ) -}}
{{- $_ := set .Values "namespaceIdentifier" ( include "django-production-chart.namespaceIdentifier" . ) -}}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaceIdentifier }}
  labels:
    app.kubernetes.io/name: {{ $.Values.releaseIdentifier }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end -}}
