{{- if (and .Values.securityPolicy.enabled .Values.securityPolicy.network.enabled) -}}
{{- $_ := set .Values "releaseIdentifier" ( include "django-production-chart.releaseIdentifier" . ) }}
{{- $_ := set .Values "namespaceIdentifier" ( include "django-production-chart.namespaceIdentifier" . ) }}
{{- $_ := set .Values "instanceIdentifier" ( include "django-production-chart.instanceIdentifier" . ) }}
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ $.Values.releaseIdentifier }}-server
  namespace: {{ $.Values.namespaceIdentifier }}
spec:
  podSelector:
{{- include "django-production-chart.netpolicy.server-pod" . | indent 4 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
{{- include "django-production-chart.netpolicy.ingress.nginx" . | indent 4 }}
{{- include "django-production-chart.netpolicy.ingress.metrics" (dict "root" .) | indent 4 }}
  egress:
{{- include "django-production-chart.netpolicy.egress.database" . | indent 4 }}
{{- include "django-production-chart.netpolicy.egress.dns" . | indent 4 }}
{{- if and .Values.deployment.enabled .Values.deploymentInitialization.enabled }}
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ $.Values.releaseIdentifier }}-deploy
  namespace: {{ $.Values.namespaceIdentifier }}
spec:
  podSelector:
{{- include "django-production-chart.netpolicy.release-job-pod" . | indent 4 }}
  policyTypes:
    - Ingress
    - Egress
  egress:
{{- include "django-production-chart.netpolicy.egress.database" . | indent 4 }}
{{- include "django-production-chart.netpolicy.egress.dns" . | indent 4 }}
{{- end }}
{{- if .Values.cronjob.enabled }}
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ $.Values.releaseIdentifier }}-cronjob
  namespace: {{ $.Values.namespaceIdentifier }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Release.Name }}
      app.kubernetes.io/component: cronjob
  policyTypes:
    - Ingress
    - Egress
  egress:
{{- include "django-production-chart.netpolicy.egress.database" . | indent 4 }}
{{- include "django-production-chart.netpolicy.egress.metrics" . | indent 4 }}
{{- include "django-production-chart.netpolicy.egress.dns" . | indent 4 }}
{{- end }}
{{- if .Values.daemon.enabled }}
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ $.Values.releaseIdentifier }}-daemon
  namespace: {{ $.Values.namespaceIdentifier }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: {{ $.Values.instanceIdentifier }}
      role: management-command-daemon
  policyTypes:
    - Ingress
    - Egress
  ingress:
{{- include "django-production-chart.netpolicy.ingress.metrics" (dict "root" . "metricsPort" 9100) | indent 4 }}
  egress:
{{- include "django-production-chart.netpolicy.egress.database" . | indent 4 }}
{{- include "django-production-chart.netpolicy.egress.dns" . | indent 4 }}
{{- end }}
{{- if .Values.memcached.enabled }}
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ $.Values.releaseIdentifier }}-memcached
  namespace: {{ $.Values.namespaceIdentifier }}
spec:
  podSelector:
{{- include "django-production-chart.netpolicy.memcached-pod" . | indent 4 }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
{{- include "django-production-chart.netpolicy.server-pod" . | indent 12 }}
      ports:
        - port: 11211
          protocol: TCP
{{- include "django-production-chart.netpolicy.ingress.metrics" (dict "root" . "metricsPort" 9150 ) | indent 4 }}
{{- end -}}
{{- if (and .Values.metrics.enabled .Values.metrics.pushgateway.enabled)  }}
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ $.Values.releaseIdentifier }}-pushgateway
  namespace: {{ $.Values.namespaceIdentifier }}
spec:
  podSelector:
{{- include "django-production-chart.netpolicy.pushgateway-pod" . | indent 4 }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
{{- include "django-production-chart.netpolicy.server-pod" . | indent 12 }}
      ports:
        - port: 9091
          protocol: TCP
    - from:
        - namespaceSelector:
            matchLabels:
              name: mci-monitoring
      ports:
        - port: 9150
          protocol: TCP
{{- end -}}
{{- end -}}
