{{- if .Values.nfsServer.enabled }}
{{- $name := printf "%s-nfs-server-%s" ( include "django-production-chart.releaseIdentifier" . ) .Values.nfsServer.name -}}
{{- $pvc_name := printf "%s-nfs-pvc-%s" ( include "django-production-chart.releaseIdentifier" . ) .Values.nfsServer.name -}}
{{- $namespace := include "django-production-chart.namespaceIdentifier" . -}}
{{- $instance := .Release.Name | quote -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  namespace: {{ $namespace }}
  labels:
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/instance: {{ $instance }}
    app.kubernetes.io/component: nfs-server
{{- include "django-production-chart.resourceLabels" . | nindent 4 }}
{{- if .Values.serviceAnnotations -}}
  annotations:
{{ toYaml .Values.serviceAnnotations | indent 4 }}
{{- end }}
spec:
  clusterIP: None
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
  selector:
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/instance: {{ $instance }}
    role: "nfs-server"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  namespace: {{ $namespace }}
  labels:
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/instance: {{ $instance }}
    app.kubernetes.io/component: nfs-server
    role: "nfs-server"
{{- include "django-production-chart.resourceLabels" . | nindent 4 }}
{{- if .Values.securityPolicy.enabled }}
  annotations:
{{- include "django-production-chart.securityPolicyAnnotations" .Values.securityPolicy.nfsServer | indent 4 }}
{{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $name }}
      app.kubernetes.io/instance: {{ $instance }}
      role: "nfs-server"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ $name }}
        app.kubernetes.io/instance: {{ $instance }}
        role: "nfs-server"
{{- if .Values.securityPolicy.enabled }}
{{- include "django-production-chart.securityPolicyAnnotations" .Values.securityPolicy.nfsServer | indent 8 }}
      annotations:
{{- end }}
    spec:
      containers:
      - name: nfs-server
        image: {{ .Values.nfsServer.image | default "us-west1-docker.pkg.dev/uwit-mci-axdd/rttl-images/nfs-server:latest" | quote }}
{{- if .Values.nfsServer.resources }}
        resources:
{{ toYaml .Values.nfsServer.resources | indent 10 }}
{{- end }}
        ports:
          - name: nfs
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /exports
            name: nfs-pvc
      volumes:
        - name: nfs-pvc
          persistentVolumeClaim:
            claimName: {{ $pvc_name }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ $pvc_name }}
  namespace: {{ $namespace }}
  labels:
    app.kubernetes.io/name: {{ $pvc_name }}
    app.kubernetes.io/instance: {{ $instance }}
    app.kubernetes.io/component: nfs-server
{{- include "django-production-chart.resourceLabels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.nfsServer.storageClassName | default "standard" | quote }}
  resources:
    requests:
      storage: {{ .Values.nfsServer.capacity }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $name }}
  namespace: {{ $namespace }}
  labels:
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/instance: {{ $instance }}
    app.kubernetes.io/component: nfs-server
{{- include "django-production-chart.resourceLabels" . | nindent 4 }}
spec:
  capacity:
    storage: {{ .Values.nfsServer.capacity }}
  accessModes:
    - ReadWriteMany
  nfs:
    server: {{ $name }}.{{ $namespace }}.svc.cluster.local
    path: "/"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $name }}
  namespace: {{ $namespace }}
  labels:
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/instance: {{ $instance }}
    app.kubernetes.io/component: nfs-server
{{- include "django-production-chart.resourceLabels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: {{ .Values.nfsServer.capacity }}
  volumeName: {{ $name }}
{{- end }}