{{- if and .Values.cronjob.enabled .Values.metrics.enabled }}
{{- $release_id := ( include "django-production-chart.releaseIdentifier" . ) }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-pushgateway" $release_id }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ printf "%s-pushgateway" $release_id }}
    helm.sh/chart: {{ include "django-production-chart.chart" . }}
    app.kubernetes.io/instance: $release_id
{{- if .Values.serviceAnnotations -}}
  annotations:
{{ toYaml .Values.serviceAnnotations | indent 4 }}
{{- end }}
spec:
  clusterIP: None
  ports:
  - name: metrics
    port: 9091
    targetPort: metrics
  selector:
    app.kubernetes.io/name: {{ printf "%s-pushgateway" $release_id }}
    app.kubernetes.io/instance: $release_id
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ printf "%s-pushgateway" $release_id }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ printf "%s-pushgateway" $release_id }}
    app.kubernetes.io/instance: $release_id
    helm.sh/chart: {{ include "django-production-chart.chart" . }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ printf "%s-pushgateway" $release_id }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  endpoints:
  - port: metrics
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-pushgateway" $release_id }}
  labels:
    app.kubernetes.io/name: {{ printf "%s-pushgateway" $release_id }}
    app.kubernetes.io/instance: $release_id
    helm.sh/chart: {{ include "django-production-chart.chart" . }}
spec:
  replicas: {{ default 1 .Values.metrics.pushgateway.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ printf "%s-pushgateway" $release_id }}
      app.kubernetes.io/instance: $release_id
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ printf "%s-pushgateway" $release_id }}
        app.kubernetes.io/instance: $release_id
    spec:
      containers:
        - name: {{ printf "%s-pushgateway" $release_id }}
          image: "prom/pushgateway:v1.2.0"
          imagePullPolicy: IfNotPresent
          ports:
            - name: metrics
              containerPort: 9091
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: 9091
            initialDelaySeconds: 10
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /-/ready
              port: 9091
            initialDelaySeconds: 10
            timeoutSeconds: 10
{{- end }}
