{{- range $name, $map := .Values.podVolumes }}
{{- if and ( hasKey $map "volume" ) ( hasKey $map.volume "claim" ) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
{{- $claimName := ( $map.claimName | default ( include "django-production-chart.pvcName" (dict "root" $ "name" $name ) ) )  -}}
{{ include "django-production-chart.pvcBase" ( dict "root" $ "name" $claimName "claim" $map.volume.claim ) }}
{{- end }}
{{- end -}}
