{{- $dot := . -}}
{{- range $name, $map := .Values.podVolumes }}
{{- if hasKey $map.volume "claim" }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
{{ include "django-production-chart.pvcBase" (dict "root" $dot "name" $name "claim" $map.volume.claim ) }}
{{- end }}
{{- end -}}
