{{- if .Values.daemon.enabled }}
{{- $dot := . -}}
{{- range .Values.daemon.daemons -}}
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: {{ printf "%s-daemon-%s" ( include "django-production-chart.releaseIdentifier" $dot ) .name }}
  labels:
    app.kubernetes.io/name: {{ include "django-production-chart.releaseIdentifier" $dot }}
    helm.sh/chart: {{ include "django-production-chart.chart" $dot }}
    app.kubernetes.io/instance: {{ $dot.Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ $dot.Release.Service | quote }}
spec:
  replicas: {{ default 1 .replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "django-production-chart.releaseIdentifier" $dot }}
      app.kubernetes.io/instance: {{ $dot.Release.Name | quote }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "django-production-chart.releaseIdentifier" $dot }}
        app.kubernetes.io/instance: {{ $dot.Release.Name }}
    spec:
{{- include "django-production-chart.specContainerBase" $dot | nindent 6 -}}
{{- include "django-production-chart.specContainerResources" $dot | nindent 10 -}}
{{- include "django-production-chart.specContainerEnv" $dot | nindent 10 -}}
{{- include "django-production-chart.specContainerCommand" (dict "command" .command "args" .args) | nindent 10 -}}
{{ printf "\n" }}
{{- end -}}
{{- end -}}