{{- $dot := . -}}
{{- $base_name := ( include "django-production-chart.releaseIdentifier" . ) }}
{{- range $type, $map := .Values.services }}
{{- $name := ( ( eq $type "ClusterIP" ) | ternary $base_name ( printf "%s-service-%s" $base_name ( lower $type ) ) ) }}
---
{{ include "django-production-chart.service" (dict "root" $dot "name" $name "type" $type "service" $map ) }}
{{- end }}
