{{- if .Values.service.enabled }}
{{- $_ := set .Values "releaseIdentifier" ( include "django-production-chart.releaseIdentifier" . ) -}}
{{- include "django-production-chart.service" (dict "root" . "name" $.Values.releaseIdentifier "type" "ClusterIP" "service" .Values.service ) }}
{{- end }}
