{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "django-production-chart.releaseIdentifier" . }}
  labels:
{{- include "django-production-chart.resourceLabels" . | nindent 4 }}
spec:
  type: {{ default "ClusterIP" .Values.service.type }}
  ports:
{{- if .Values.service.ports }}
{{- range .Values.service.ports }}
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ default "TCP" .protocol }}
      name: {{ .name }}
{{- end }}
{{- else }}
    - port: {{ default 80 .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
{{- end }}
  selector:
    app.kubernetes.io/name: {{ include "django-production-chart.releaseIdentifier" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
