{{- if .Values.service.enabled }}
{{- $name := ( include "django-production-chart.releaseIdentifier" . ) }}
{{- include "django-production-chart.service" (dict "root" . "name" $name "type" "ClusterIP" "service" .Values.service ) }}
{{- end }}
