{{- if and .Values.service.enabled .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "django-production-chart.releaseIdentifier" . }}
spec:
  endpoints:
    - port: {{ default "http" .Values.metrics.serviceMonitor.port }}
  selector:
    matchLabels:
{{- include "django-production-chart.baseLabels" . | nindent 6 }}
{{- end }}
