{{- if and ( or .Values.service.enabled (hasKey .Values "services" )) .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
{{- $_ := set .Values "releaseIdentifier" ( include "django-production-chart.releaseIdentifier" . ) -}}
{{- $_ := set .Values "namespaceIdentifier" ( include "django-production-chart.namespaceIdentifier" . ) -}}
{{- $_ := set .Values "instanceIdentifier" ( include "django-production-chart.instanceIdentifier" . ) -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ $.Values.releaseIdentifier }}
  namespace: {{ $.Values.namespaceIdentifier }}
  labels:
    app.kubernetes.io/name: {{ $.Values.releaseIdentifier }}
    app.kubernetes.io/instance: {{ $.Values.instanceIdentifier }}
    app.kubernetes.io/component: servicemonitor
{{- include "django-production-chart.resourceLabels" . | nindent 4 }}
spec:
  endpoints:
    - port: {{ default "http" .Values.metrics.serviceMonitor.port }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ $.Values.instanceIdentifier }}
{{- end }}
