{{- $_ := set .Values "releaseIdentifier" ( include "django-production-chart.releaseIdentifier" . ) -}}
{{- range $type, $map := .Values.services }}
{{- $name := ( ( eq $type "ClusterIP" ) | ternary $.Values.releaseIdentifier ( printf "%s-service-%s" $.Values.releaseIdentifier ( lower $type ) ) ) }}
---
{{ include "django-production-chart.service" (dict "root" $ "name" $name "type" $type "service" $map ) }}
{{- end }}
