{{- if .Values.statefulset.enabled }}
{{ $_ := set .Values "releaseIdentifier" ( include "django-production-chart.releaseIdentifier" . ) }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.releaseIdentifier }}
  namespace: {{ include "django-production-chart.namespaceIdentifier" . }}
  labels:
    app.kubernetes.io/name: {{ .Values.releaseIdentifier }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: statefulset
{{- include "django-production-chart.resourceLabels" . | nindent 4 }}
{{- if .Values.securityPolicy.enabled }}
{{- if .Values.securityPolicy.statefulset }}
{{- if .Values.securityPolicy.statefulset.skipCheck }}
  annotations:
{{- range $index, $value:= .Values.securityPolicy.statefulset.skipCheck }}
    checkov.io/skip{{ add $index 1 }}: {{ $value | quote }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
spec:
{{- if not .Values.autoscaling.enabled }}
  serviceName: {{ .Values.releaseIdentifier }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.releaseIdentifier }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.releaseIdentifier }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: statefulset
{{- include "django-production-chart.resourceLabels" . | nindent 8 }}
{{- if .Values.securityPolicy.enabled }}
{{- if .Values.securityPolicy.statefulset }}
{{- if .Values.securityPolicy.statefulset.annotations }}
      annotations:
{{ toYaml .Values.securityPolicy.statefulset.annotations | indent 8 }}
{{- end }}
{{- end }}
{{- end }}
    spec:
{{- if .Values.statefulset.affinityTemplate  }}
      affinity:
{{ tpl .Values.statefulset.affinityTemplate . | trim | indent 8 }}
{{- end }}
{{- if .Values.securityPolicy.enabled }}
{{- if .Values.securityPolicy.statefulset }}
{{- if .Values.securityPolicy.statefulset.spec }}
{{ toYaml .Values.securityPolicy.statefulset.spec | indent 6 }}
{{- end }}
{{- end }}
{{- end }}
{{ include "django-production-chart.specControllerScheduling" . | indent 6 }}
{{ include "django-production-chart.specContainer" . | indent 6 }}
{{ include "django-production-chart.specContainerLifecycle" . | indent 10 }}
{{ include "django-production-chart.specContainerProbes" . | indent 10 }}
{{ include "django-production-chart.specContainerSidecars" . | indent 6 }}
{{- $i := 0 }}
{{- range $name, $map := .Values.podVolumes }}
{{- if hasKey $map.volume "claimTemplate" }}
{{- if eq $i 0 }}
  volumeClaimTemplates:
{{- end }}
{{- $i = add1 $i }}
{{- end }}
{{- end }}
{{- range $name, $map := .Values.podVolumes }}
{{- if hasKey $map.volume "claimTemplate" }}
{{ include "django-production-chart.pvcBase" (dict "root" $ "name" $name "claim" $map.volume.claimTemplate ) | indent 4 }}
{{- end }}
{{- end }}
{{- end -}}
