{{- if .Values.statefulset.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "django-production-chart.releaseIdentifier" . }}
  namespace: {{ include "django-production-chart.namespaceIdentifier" . }}
  labels:
    app.kubernetes.io/component: statefulset
    app.kubernetes.io/name: {{ include "django-production-chart.releaseIdentifier" . }}
    helm.sh/chart: {{ include "django-production-chart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- if .Values.securityPolicy.enabled }}
{{- if .Values.securityPolicy.statefulset }}
{{- if .Values.securityPolicy.statefulset.skipCheck }}
  annotations:
{{- range $index, $value:= .Values.securityPolicy.statefulset.skipCheck }}
    checkov.io/skip{{ add $index 1 }}: {{ $value | quote }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
spec:
{{- if not .Values.autoscaling.enabled }}
  serviceName: {{ include "django-production-chart.releaseIdentifier" . }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "django-production-chart.releaseIdentifier" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "django-production-chart.releaseIdentifier" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
{{- if .Values.securityPolicy.enabled }}
{{- if .Values.securityPolicy.statefulset }}
{{- if .Values.securityPolicy.statefulset.annotations }}
      annotations:
{{ toYaml .Values.securityPolicy.statefulset.annotations | indent 8 }}
{{- end }}
{{- end }}
{{- end }}
    spec:
{{- if .Values.securityPolicy.enabled }}
{{- if .Values.securityPolicy.statefulset }}
{{- if .Values.securityPolicy.statefulset.spec }}
{{ toYaml .Values.securityPolicy.statefulset.spec | indent 6 }}
{{- end }}
{{- end }}
{{- end }}
{{- include "django-production-chart.specControllerScheduling" . | nindent 6 -}}
{{- include "django-production-chart.specContainer" . | nindent 6 -}}
{{- include "django-production-chart.specContainerLifecycle" . | nindent 10 -}}
{{- include "django-production-chart.specContainerProbes" . | nindent 10 -}}
{{- include "django-production-chart.specContainerSidecars" . | indent 6 -}}
{{- $i := 0 }}
{{- range $name, $map := .Values.podVolumes }}
{{- if hasKey $map.volume "claimTemplate" }}
{{- if eq $i 0 }}
  volumeClaimTemplates:
{{- end }}
{{- $i = add1 $i }}
{{- end }}
{{- end }}
{{- $dot := . }}
{{- range $name, $map := .Values.podVolumes }}
{{- if hasKey $map.volume "claimTemplate" }}
    - metadata:
{{ include "django-production-chart.pvcBase" (dict "root" $dot "name" $name "claim" $map.volume.claimTemplate ) | indent 6 }}
{{- end }}
{{- end }}
{{- end -}}
